from controllers.client import ClientController
from controllers.bank_account import BankAccountController
from controllers.payment import PaymentController
from controllers.project import ProjectController
from controllers.dachboard import DashboardController
from controllers.transaction import TransactionController
from controllers.spending import SpendingController